### ISSUE TITLE
Where can I found the source code for Autofac.Extras.AggregateService 3.0.4 ?

### ISSUE THREAD

**Issue by sgustafsson** [autofac/Autofac.Extras.AggregateService#2]
This github repo only hosts the 4.0.0 relase, is the source code for 3.0.4 available somewhere else?

cheers
S

**Comment by tillig** [comment]
You'll have to go back in history on the core Autofac repo - https://github.com/autofac/Autofac

Everything used to be in a single repo on Google Code. When that shut down and we moved to GitHub, that's also when we split repositories. Due to the "single repo" thing, there aren't tags for individual components, so unfortunately you'll have to do some spelunking to find the right commit for the version you're looking for.

We split repos on GitHub to make this exact sort of question easier to answer. Unfortunately it's not retroactive for past versions.
